import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Lock } from "lucide-react";
import { useStore } from "../context/StoreContext";

export default function Checkout(){
 const {cart,cartTotal,notify}=useStore(); const navigate=useNavigate(); const [form,setForm]=useState({name:"",phone:"",address:"",city:"",pin:"",payment:"card"}); const [errors,setErrors]=useState({});
 const update=k=>e=>setForm({...form,[k]:e.target.value});
 const submit=e=>{e.preventDefault();let er={};["name","phone","address","city","pin"].forEach(k=>{if(!form[k].trim())er[k]="Required"});if(form.pin&&!/^\d{6}$/.test(form.pin))er.pin="Enter 6-digit PIN";setErrors(er);if(!Object.keys(er).length){localStorage.removeItem("woodora-cart");notify("Order placed successfully");navigate("/order-success")}};
 if(!cart.length)return <div className="container-fluid py-24 text-center"><h1 className="text-3xl font-black">Your cart is empty</h1><Link to="/products" className="mt-6 inline-block text-[#8b6f47]">Shop now</Link></div>;
 const delivery=cartTotal>=10000?0:499,total=cartTotal+delivery;
 return <div className="container-fluid py-10"><h1 className="text-4xl font-black">Checkout</h1><form onSubmit={submit} className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="rounded-2xl border border-[#e7e1d7] bg-white p-6 dark:bg-[#211f1b]"><h2 className="text-xl font-bold">Delivery address</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["name","Full name"],["phone","Phone number"],["city","City"],["pin","PIN code"]].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={update(k)} error={errors[k]}/>)}</div><div className="mt-4"><label className="text-sm font-semibold">Address</label><textarea value={form.address} onChange={update("address")} rows="4" className="mt-2 w-full rounded-xl border border-[#d9d1c5] bg-transparent px-4 py-3 outline-none focus:border-[#8b6f47]"/>{errors.address&&<p className="text-xs text-red-500">{errors.address}</p>}</div><h2 className="mt-8 text-xl font-bold">Payment</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{["card","upi","cod"].map(p=><label key={p} className={`rounded-xl border p-4 text-sm font-semibold ${form.payment===p?"border-[#8b6f47] bg-[#f0eadf] dark:bg-[#2b2822]":"border-[#d9d1c5]"}`}><input type="radio" name="payment" value={p} checked={form.payment===p} onChange={update("payment")} className="mr-2 accent-[#8b6f47]"/>{p==="cod"?"Cash on delivery":p.toUpperCase()}</label>)}</div></div><div className="h-fit rounded-2xl bg-[#f0eadf] p-6 dark:bg-[#211f1b]"><h2 className="text-xl font-bold">Order summary</h2><div className="mt-5 space-y-3">{cart.map(i=><div key={i.id} className="flex justify-between gap-3 text-sm"><span>{i.name} × {i.quantity}</span><span>₹{(i.price*i.quantity).toLocaleString("en-IN")}</span></div>)}</div><div className="mt-6 border-t border-black/10 pt-5 text-sm dark:border-white/10"><div className="flex justify-between"><span>Subtotal</span><span>₹{cartTotal.toLocaleString("en-IN")}</span></div><div className="mt-3 flex justify-between"><span>Delivery</span><span>{delivery?"₹499":"Free"}</span></div><div className="mt-4 flex justify-between text-lg font-black"><span>Total</span><span>₹{total.toLocaleString("en-IN")}</span></div></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#29251f] py-3.5 font-bold text-white"><Lock size={16}/> Place order</button></div></form></div>;
}
function Field({label,value,onChange,error}){return <div><label className="text-sm font-semibold">{label}</label><input value={value} onChange={onChange} className="mt-2 w-full rounded-xl border border-[#d9d1c5] bg-transparent px-4 py-3 outline-none focus:border-[#8b6f47]"/>{error&&<p className="mt-1 text-xs text-red-500">{error}</p>}</div>}