import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useStore } from "../context/StoreContext";

export default function Signup(){
 const [form,setForm]=useState({name:"",email:"",password:"",confirm:""}); const [errors,setErrors]=useState({}); const {notify}=useStore(); const navigate=useNavigate();
 const update=k=>e=>setForm({...form,[k]:e.target.value});
 const submit=e=>{e.preventDefault();const er={};if(form.name.trim().length<2)er.name="Enter your name";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))er.email="Enter a valid email";if(!/^(?=.*[A-Za-z])(?=.*\d).{8,}$/.test(form.password))er.password="Use 8+ characters with a letter and number";if(form.confirm!==form.password)er.confirm="Passwords do not match";setErrors(er);if(!Object.keys(er).length){notify("Account created successfully");navigate("/")}};
 return <div className="container-fluid grid min-h-[70vh] place-items-center py-14"><div className="w-full max-w-md rounded-3xl border border-[#e7e1d7] bg-white p-7 dark:bg-[#211f1b] sm:p-9"><div className="text-center"><Link to="/" className="text-xl font-black tracking-[.2em]">WOODORA</Link><h1 className="mt-7 text-3xl font-black">Create account</h1><p className="mt-2 text-sm text-gray-500">Join WOODORA and save your favourites.</p></div><form onSubmit={submit} className="mt-8 space-y-4">{[["name","Full name","Your name"],["email","Email","you@example.com"],["password","Password","8+ chars, letter + number"],["confirm","Confirm password","Repeat password"]].map(([k,l,p])=><div key={k}><label className="text-sm font-semibold">{l}</label><input type={k.includes("password")||k==="confirm"?"password":k} value={form[k]} onChange={update(k)} placeholder={p} className="mt-2 w-full rounded-xl border border-[#d9d1c5] bg-transparent px-4 py-3 outline-none focus:border-[#8b6f47]"/>{errors[k]&&<p className="mt-1 text-xs text-red-500">{errors[k]}</p>}</div>)}<button className="w-full rounded-xl bg-[#29251f] py-3.5 font-bold text-white">Create account</button></form><p className="mt-6 text-center text-sm text-gray-500">Already have an account? <Link to="/login" className="font-bold text-[#8b6f47]">Sign in</Link></p></div></div>
}